[package]
name = "rust_interop"
version = "0.1.0"
edition = "2021"

[dependencies]
bellman = { version = "0.14", features = [] }
bls12_381 = "0.8"
ff = "0.13"
pairing = "0.23"
rand = "0.8"
sha2 = "0.10"
libc = "*"
bincode = "*"
serde = "*"
serde_bytes = "0.11"

[lib]
crate-type = ["cdylib"]
